nodes:
  "parietal lobe; occiptal lobe; temporal lobe"
relay_station: "none"
sample_rate: 1000
t_lags: 300
t_secs: 500
t_burnit: 10
noise_color: "pink"
std_noise: 2700
dist_shape: -0.25
dist_scale: 0.09
dist_location: 0.25
dist_trunc_percent: 0.0
model_name: "Simulation #3 (pink)"
custom_connectivity: True
